name: Build Pacman Package
on:
  workflow_dispatch:
    inputs:
      package-name:
        description: "Name of the package being built"
        required: true
        type: string
      flutter:
        description: "Whether to install Flutter for build"
        required: false
        type: boolean
        default: false
  workflow_call:
    inputs:
      package-name:
        description: "Name of the package being built"
        required: true
        type: string
      flutter:
        description: "Whether to install Flutter for build"
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout package repo
      uses: actions/checkout@v4

    - name: Build package inside Arch container
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace archlinux:latest /bin/bash -c "
          # Create non-root user
          useradd -m builder
          passwd -d builder

          # Install dependencies
          pacman -Syu --noconfirm
          pacman -S --needed --noconfirm \
            base-devel git meson gtk3 adwaita-fonts \
            arch-install-scripts fakeroot pkgconf sudo rsync
          if [ "${{ inputs.flutter }}" = "true" ]; then
            pacman -S --needed --noconfirm unzip curl clang cmake ninja

            # Install Flutter SDK manually
            curl -fL https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.41.4-stable.tar.xz -o flutter.tar.xz
            file flutter.tar.xz
            tar -xf flutter.tar.xz
            mv flutter /opt/flutter
            chown -R builder:builder /opt/flutter
          fi

          pacman -Scc --noconfirm
          echo 'builder ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

          # Switch to builder
          su - builder -c '
            set -e
            export PATH=/opt/flutter/bin:$PATH
            FLUTTER=${{ inputs.flutter }}
            
            mkdir -p /home/builder/build
            rsync -a --exclude=\".git\" /workspace/ /home/builder/build/
            cd /home/builder/build

            if [ \"$FLUTTER\" = \"true\" ]; then
              flutter precache --linux
            fi

            # Optionally: generate b2sums
            # makepkg -g >> PKGBUILD
            makepkg -sf --noconfirm

            sudo cp ./*.pkg.tar.* /workspace/
          '
        "

    - name: Upload built package to workflow artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.package-name }}
        path: ./*.pkg.tar.*

    - name: Checkout binary repo
      uses: actions/checkout@v4
      with:
        repository: JappeOS/jappeos-repo
        token: ${{ secrets.JAPPEOS_ORG_PAT }}
        ref: gh-pages
        path: jappeos-repo

    - name: Add package to repo
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace -v ${{ github.workspace }}/jappeos-repo:/repo -w /repo archlinux:latest /bin/bash -c "
          pacman -Syu --needed --noconfirm pacman-contrib
          mkdir -p josrepo
          # Copy built packages from workspace into repo
          cp /workspace/*.pkg.tar.* josrepo/
          cd josrepo
          repo-add -R josrepo.db.tar.gz *.pkg.tar.*
        "

    - name: Commit and push updates
      run: |
        cd jappeos-repo
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add josrepo/
        git commit -m "Update ${{ inputs.package-name }}"
        git push
